# Generated by Django 6.0.6 on 2026-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('service', models.CharField(choices=[('website', 'Web sitesi tasarımı ve geliştirme'), ('backend', 'Backend ve API geliştirme'), ('consulting', 'Teknik danışmanlık'), ('automation', 'Süreç otomasyonu')], max_length=20, verbose_name='Hizmet')),
                ('description', models.TextField(max_length=1500, verbose_name='Proje açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
            ],
            options={
                'verbose_name': 'Hizmet talebi',
                'verbose_name_plural': 'Hizmet talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
